### ISSUE TITLE
Array data storage in neo4j

### ISSUE THREAD

**Issue by akarsh** [akarsh/TUPJNOSQL17#14]
To store the data in neo4j 

![screen shot 2017-07-07 at 15 20 24](https://user-images.githubusercontent.com/845598/27959463-d23bfd44-6327-11e7-95ba-4950b7de7e1a.png)

issue link opened for pluging
#https://github.com/srfrnk/moneo/issues/4

**Comment by akarsh** [comment]
Data storage is now done in neo4j.


Still one unknown error
 ` '(m {' + 'mongoId:\'' + mongoId2.toHexString() + '\'' + '}' + ' ) ' +`
Line 99 from [ function createRelation](https://github.com/srfrnk/moneo/blob/master/moneo.js). This is related to the plugin.

When does this error popup ?
during signup.

**Comment by sameersubudhi** [comment]
This issue is now fixed. Check my latest check in.
